### ISSUE TITLE
Unexpected exception on Bad Request.

### ISSUE THREAD

**Issue by Pipepito** [Nexmo/nexmo-dotnet#116]
### General description of the issue or question
When a request is sent and is not properly formatted (or missing values or has bad data) the response that comes from the API is BadRequest (Obviously), but the SDK isn't handling it and throws an exception.

### Which target framework(s) of .NET can you reproduce this issue against?
.NET Core 2.0, .NET Framework 4.6.1

### Version or commit hash
Which version(s) of `CSharp.Nexmo.Client` did you encounter this issue?
 3.2.0

### Expected Behavior
What should have happened?
Anything except an exception, library should handle other results than 200.

### Actual Behavior
What actually happened?
A bad request result was sent to the SDK from NexmoAPI, nexmo SDK tried to deserialize the value (which is empty) and crashes producing a misleading exception.

Parameter name: value

  at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

  at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)

### Steps to Reproduce
When sending a new call to Nexmo 
```
client.Call.Do(new Call.CallCommand
            {
                to = new[]
                {
                    new Call.Endpoint {
                        type = "phone",
                        number = 00353xxxxxxxxx
                    }
                },
                from = new Call.Endpoint
                {
                    type = "phone",
                    number = 00353xxxxxxxxx
                },
                answer_url = new[]
                {
                    answerUrl
                },
                event_url = new[]
                {
                    callBack
                },

            });
```
enter a number with the wrong format (for example msisdn format with 00 at the front) into the to or from fields, request will fail and throwing the exception mentioned above.

**Comment by cirojr** [comment]
Hi @Pipepito! No one likes exceptions, indeed.
I'll take a look.

**Comment by smithrobs** [comment]
In ApiRequest and VersionedApiRequest, if the send task result is `!(IsSuccessStatusCode)`, then the `NexmoResponse` object does not have `JsonResponse` populated - it's null. Likewise, `DoRequest` can return null/empty. Most (all?) of the "API endpoint" classes (Account, Number, SMS, etc.) expect the JSON response to be properly formed JSON.

   The configuration option `Nexmo.Api.EnsureSuccessStatusCode` will force these exceptions to be slightly more informative.

   In keeping with the general spirit of the library, I agree this specific use case should be handled more gracefully. That said, it will be tough to change the public method signatures without breaking backward compatibility. Perhaps the best short-term solution is to add null/status checks in each and every "API endpoint" class method. If the JSON response doesn't exist, we'll return a default instance of the return object.

   Historically, users of the library have been encouraged to enable debug logging and implement their own retry logic as they see fit.

   We'll gladly help out with a PR if someone wants to take this on (@cirojr ?) otherwise I will self-assign and do something similar as described above.

**Comment by cirojr** [comment]
Thanks for the directions @smithrobs. I'd like to contribute with it.
I'll take a look at the structure, keeping what you've pointed in mind.

**Comment by slorello89** [comment]
#187

**Comment by slorello89** [comment]
Hi @Pipepito - FYI as of version 5.0.0, the SDK will now throw exceptions with a status code and a best-attempt description of what went wrong. I'm closing out this issue - if you continue to encounter it please feel free to reopen.

thanks,
