### ISSUE TITLE
unable to install 3.0.0 to 3.2.2 with a project that targets .net 4.5.0

### ISSUE THREAD

**Issue by Druvo** [Nexmo/nexmo-dotnet#138]
Hi there, I am using asp.net MVC in Dot NETFramework 4.5.0 that's why Nexmo version 3.0.0 to 3.2.2 are not working in my application because the targeted version is NETFramework 4.5.2. but when I goto lower versions it also not working for the dependency. Some dependencies are also targeted at NETFramework 4.5.2. can anyone help me with this problem?

**Comment by smithrobs** [comment]
The list of frameworks the library supports is in the [README](https://github.com/Nexmo/nexmo-dotnet/blob/master/README.md).

"Support for .NET Framework 4, 4.5, and 4.5.1 ended on January 12, 2016. Microsoft recommends customers upgrade to .NET Framework 4.5.2 in order to continue to receive technical support and security updates. For more information, please visit the .NET Framework Support Lifecycle Policy FAQ https://support.microsoft.com/help/17455."

(https://support.microsoft.com/en-us/lifecycle/search/548)

Microsoft no longer supports v4.5 and therefore this library does not support v4.5. If someone wants to take the risk of altering the source locally and targeting unsupported frameworks, they are free to do so. This library will not.
