### ISSUE TITLE
Target framework versions earlier than 4.5.2?

### ISSUE THREAD

**Issue by AnturGyffrous** [Nexmo/nexmo-dotnet#3]
What is the point of targeting version 4.5.2 of the .NET framework if you're not making any use of the features in that version?

Indeed, you're not using asynchronous calls so don't even need to target version 4.5. You could easily change this to version 4.0 of the framework and loose no features at all, a cursory glance at the code suggests you could get away with an older version than that.

I get that Visual Studio 2015 targets 4.5.2 by default, but you are creating a publicly consumable component, by sticking with this default you are limiting your user-base.

**Comment by smithrobs** [comment]
Primarily because 4, 4.5, and 4.5.1 are no longer officially supported by Microsoft. [1] I felt it important to do my part in helping nudge people off unsupported versions. That said, I agree it is possible to target older versions for those that absolutely cannot upgrade for whatever reason. I will discuss this with the team. In the meantime, if you are so inclined please feel free to submit a PR to support 3.5 SP1 - I believe that is still supported for most if not all Windows versions until 2020.

Thanks for the question!

[1] - https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by AnturGyffrous** [comment]
Thanks for the quick reply, I'll see about a PR as time permits.
