### ISSUE TITLE
You must provide at least one type of authentication via configuration

### ISSUE THREAD

**Issue by jacob8000** [Nexmo/nexmo-dotnet#67]
I know there is a closed issue with the same title but this is totally different issue.
I recently tried to embed Nexmo API in our systems.
We use Nexmo API to send SMS messages.

Everything works well in WinForm and Console application.
However, when we switch to WS service, we get this exception:

> System.TypeInitializationException: The type initializer for 'Nexmo.Api.Configuration' threw an exception. ---> System.ArgumentException: You must provide at least one type of authentication via configuration!\r\n   at Nexmo.Api.Configuration..ctor()\r\n   at Nexmo.Api.Configuration..cctor()\r\n   --- End of inner exception stack trace ---\r\n   at Nexmo.Api.Configuration.get_Instance()\r\n   at Nexmo.Api.Request.ApiRequest.GetBaseUriFor(Type component, String url)\r\n   at Nexmo.Api.SMS.Send(SMSRequest request, Credentials creds)\r\n   at NotificationServer.Senders.SMS.SMS_Nexmo.SMSSender_Nexmo.SendSMS(SendSMSRequest request)

```
SMSRequest req = new SMSRequest();
req.from = "";
req.text = "message"
req.type = "unicode";

Nexmo.Api.Request.Credentials crd = new Nexmo.Api.Request.Credentials();
crd.ApiKey = "API_KEY";
crd.ApiSecret = "API_SECRET";
response = Nexmo.Api.SMS.Send(req, crd);
```

web.config:

add key="Nexmo.UserAgent" value="myApp/1.0" />
add key="Nexmo.Url.Rest" value="https://rest.nexmo.com" />
add key="Nexmo.Url.Api" value="https://api.nexmo.com" />
add key="Nexmo.api_key" value="" />
add key="Nexmo.api_secret" value="" />

**Comment by smithrobs** [comment]
Are you using v2.2.2? This is fixed in the v3.0 pre-releases.

The problem in v2.2.2 exists because of [this code](https://github.com/Nexmo/nexmo-dotnet/blob/master/Nexmo.Api/Configuration.cs#L75). If for any reason your configuration file is not found (which it sounds like it isn't) then the library will throw the exception.

The history of this choice is long - we wanted to keep in-line with .NET's focus on configurability. Then .NET Core came along and XML config was not built-in, so we tried to make it work but the number of environment combinations now available (cross-plat, IIS vs Kestrel vs other hosting, security settings) make it onerous to support when the majority of users inform us that they want to handle credentials on their own.

We have a few options:

1. Move to v3.0 even though it's still technically in pre-release. The exception is not thrown.
2. Remove the thrown exception mentioned above and release v2.2.3 (I might do this anyway as there are other minor issues to address before v3.0 is officially released.)
3. Determine why the environment your WS is running in isn't recognizing the configuration. [Logging may be useful here](https://github.com/Nexmo/nexmo-dotnet#logging).

**Comment by jacob8000** [comment]
Thank you for your reply.
Where can I find a build of version 3.0 (I can not build it by myself as we don't have VS2017 here, only 2015).
Thank you

**Comment by smithrobs** [comment]
Sure. You can install the latest prerelease via Nuget:

`Install-Package Nexmo.Csharp.Client -Version 3.0.0-pre3`

**Comment by jacob8000** [comment]
What an amazing and fast support!
It works well now.
Thank you very much!
