### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by cataliz3er** [Nexmo/nexmo-dotnet#72]
Lately I'm getting this exception:

MissingMethodException: Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.

![capture](https://user-images.githubusercontent.com/16380896/33071139-0be8906e-cec3-11e7-8d92-1be1ca2c95fb.PNG)

Any ideas?
Thank you

**Comment by smithrobs** [comment]
I need to know a bit more about your environment and program to be sure, but this is _probably_ related to #40 and the breaking changes in `Microsoft.Extensions.DependencyInjection`.

Which version of `Nexmo.Csharp.Client` are you using?
Which version of `Microsoft.Extensions.DependencyInjection` are you using?
Which version of .NET Framework/Core/Standard and which platform (Win/Mac/Linux)?

Feel free to attach your `project.json` or contact me on the Nexmo slack.

**Comment by cataliz3er** [comment]
Nexmo.Csharp.Client v3.0.0-pre2
Microsoft.Extensions.DependencyInjection v2.0.0
.NET Framework 4.6.1 Windows

The latest change I made to the project was upgrading from 4.6.0 to 4.6.1 because other 3rd party packages required this.

**Comment by smithrobs** [comment]
Thank you. Yes, this is because of `Microsoft.Extensions.DependencyInjection`. MS made a breaking change with v2.0 of this lib which requires a rebuild of any consuming libs. Currently, `Nexmo.Csharp.Client` v3.0.0 builds against the following:

.NET Target | `Microsoft.Extensions.DependencyInjection`
------------|-------------
net452|1.0.2
net46|1.0.2
net461|1.0.2
net462|1.0.2
netstandard1.6|1.0.2
netstandard2.0|2.0.0

This means that in order to use the Nexmo lib and `Microsoft.Extensions.DependencyInjection` v2.0.0 you currently have to have your project target netstandard2.0 **OR** someone (you, me, someone else) compiles the Nexmo lib target net461 against 2.0.0  **OR** you downgrade your assembly to DI v1.0.2.

I am open to better ideas about how to handle this! The [Orleans framework](https://github.com/dotnet/orleans) ran into the same issue (see their issue 3325) and from what I've read there aren't any great solutions that are transparent to everyone using the library. They ended up making a breaking change themselves. That is what I'm thinking of doing for v3.0 final: **Force every .NET target to use `Microsoft.Extensions.DependencyInjection` v2.0.0**

This library only uses DI for logging, so we **could** drop the DI use altogether. #9 contains some history of the decisions made with respect to logging. The idea was to use what MS provides but I understand that the breakage is frustrating...

**Comment by cataliz3er** [comment]
The simplest solution was to downgrade DI to v1.0.2, but now I'm getting this exception:

FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=1.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by smithrobs** [comment]
The assembly loader found a version of `Microsoft.Extensions.DependencyInjection` but it didn't match the reference (wrong version, culture, key, etc.). Maybe it's still finding the v2.0 DI assembly somewhere?

**Comment by cataliz3er** [comment]
Found the problem
Had to comment out these lines
![capture](https://user-images.githubusercontent.com/16380896/33170234-376ef9e2-d050-11e7-84f0-2565fcc50103.PNG)
Now it works. Thanks for the assist :)
