### ISSUE TITLE
C# - Nexmo APIs - Clarifications

### ISSUE THREAD

**Issue by sivasubramanianservion** [Nexmo/nexmo-dotnet#73]
Team,
We are trying to setup IVR using nexmo using C# API. While trying to setup the behaviour for the below scenario, we have a clarifications:
Scenario:
-----------
1. On the answering the call, play some messages to the customer. 
2. Collect the input from the caller
3. In case no input or no match scenarios, the respective messages needs to be played.
4. Then proceed to collect the input.
5. All the no match/input messsages,the number of retries is also dynamic.
Clarifications:
1. For the Call.EditCommand , for the action we need to specify only the action verb alone. Where do we need to set the input URL for the input.
For example,
var CallEditCommandResponse = Call.Edit(callId, new Call.CallEditCommand
{
action = "input"
});
2. For the call command , Is it mandatory to give Threading.sleep command between BeginTalk/Stream to End Talk/Stream.
3. Some times , we are gettitng Value parameter cannot be null for the End Talk/Stream command.
4. Also for the input timed-out scenario/event, we are getting only the conversation_uuid. We are not getting the uuid(callid). While trying to retrieve using Call.SearchFilter as below, we are getting the error like object not set,etc.
var calls = Call.List(new Call.SearchFilter
{
conversation_uuid = input.conversation_uuid,
page_size = 3
});
Note: also tried with the page_size as 10 as well.
Thanks,
M. Sivasubramanian.

**Comment by sivasubramanianservion** [comment]
From Pt. 1 - 5 is the scenario. From Point no 6 onwards the list of clarifications we have.

**Comment by smithrobs** [comment]
Some of these clarifications would be better answered by Nexmo support. Feel free to send your questions to support@nexmo.com and reference this issue.

6. I _think_ that would go into your NCCO doc. See [here](https://developer.nexmo.com/tutorials/interactive-voice-response#request-user-input-via-ivr) for a possible example.
7. It would depend on what you want to do. I would have to know more about your scenario. Nexmo Support would probably answer this better.
8. This is usually a (rather unclear to you) indication that Nexmo rejected your request. If you are using v2.3.0 you may set the configuration option `Nexmo.Api.EnsureSuccessStatusCode` to true in order to receive a clearer exception detailing the failure. Note that this throws an exception so your code needs to react accordingly.
9. To clarify: You are not receiving the uuid from the Call.List CallResponse object?

**Comment by sivasubramanianservion** [comment]
Team,

Thanks for your response.

Please find below the in-line responses.

Thanks,
M. Sivasubramanian.
