### ISSUE TITLE
Nexmo.Api/Jwt.cs expects string / path?

### ISSUE THREAD

**Issue by iDoApp** [Nexmo/nexmo-dotnet#88]
Nexmo.Api/Jwt.cs seems to have some confusion? Or I am missing something?

            var pemContents = File.ReadAllText(privateKey);
            var rsa = PemParse.DecodePEMKey(pemContents);

OR

            var rsa = PemParse.DecodePEMKey(privateKey);

What to be used?

Though the method sign. says "CreateToken(string appId, string privateKey)" there is no mean to set this key. as wherever it is consumed, it is done with / as Jwt.CreateToken(appId, appKeyPath) 
(please notice it expects appKey"Path").

Please advice

**Comment by smithrobs** [comment]
This is a breaking change made in v3.0. Per the release notes:

> __[BREAKING]__ ApplicationKey must now be the actual private key and not a path to the key.

The reasoning for this change is to increase library flexibility in cases of lower-trust environments.

If you use a version of the library that is >= 3.0, you must provide the **contents** of your key file and not a path to it. We tried to do what we could to make this clear in the release notes. The thought of adding a check that the user passed in a path instead of a RSA file was a thought, but I left it out for now.

In summary, for v3.0+ you must do something like this:

```csharp
var creds = new Nexmo.Api.Request.Credentials {
                ApplicationId = "ffffffff-ffff-ffff-ffff-ffffffffffff",
                ApplicationKey = System.IO.File.ReadAllText("private.key")
            };
            var client = new Nexmo.Api.Client(creds);

            var results = client.Call.Do(new Call.CallCommand
            {
                to = new[]
                {
                    new Call.Endpoint
                    {
                        type = "phone",
                        number = "15556667777"
                    }
                },
                @from = new Call.Endpoint
                {
                    type = "phone",
                    number = "15556668888"
                },
                answer_url = new[]
                {
                    "https://nexmo-community.github.io/ncco-examples/first_call_talk.json"
                }
            });
```
