### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by smithrobs** [Nexmo/nexmo-dotnet#9]
[Reference](https://github.com/Nexmo/client-library-specification)

Troubleshooting failed API requests can be difficult, so access to logs are invaluable. Logging:
- [x] Should use language / runtime standard log if available and generally used.
- [x] Must be configurable:
  - [x] Can be disabled / enabled
  - [x] Verbosity can be defined.
- [x] Can delegate configuration to a logging interface if generally used.

**Comment by rajanadar** [comment]
hey @smithrobs 

a few thoughts on this item.. let me know if it sounds crazy :)

in terms of the checklist above, i think .NET doesn't have an in-built logging framework. you would have to start out with an external dependency.

personally, i think a library's best use is to do its core thing, which is "connect to its http service" and abstract out the types and logistics.  and in case of any errors, throw a clear exception to the caller.

it is probably better for the caller of the library to handle the logging aspect of the flow instead of the library itself, because:

1. logging involves taking a dependency on logging frameworks. it gets annoying when a library dictates this, instead of the target host application. you can end up with varying versions of logging frameworks or worse, different logging frameworks.
2. also, the library will now start doing logging/config management, instead of its core concern.
3. some clients may not care about logging. now we have forced it upon them. (Json.Net is probably the only dependency that consumers are okay with, when consuming an http sdk)
4. more often than not, consumers have specific logging formats so that it is easy for ingestion in their logging products. (splunk, cosmos etc.)

overall, logging starts out trivially and becomes this slice of a sdk, which is not its core concern.
as long as the library clearly throws an exception (capturing 400 Bad Requests with error messages, json parsing etc.) the consumers should be able to handle it like any other layer of classes they would have in their application.

so the whole onus of logging can be deferred to the consumer of the library.

**Comment by tjlytle** [comment]
If logging is external, the client library should at least allow access to the raw HTTP request / response, so the external code has enough information to create a useful log.

Is there no standard logging interface in .NET? @rajanadar Would it be reasonable to define a simple logging interface (expect a method that takes `level` and `message`) that would allow a simple wrapper around an existing (custom or otherwise) logging system?

**Comment by rajanadar** [comment]
yeah @tjlytle .. an optional custom logging interface will work... but personally i have never been a big fan of it. it always means that the consumer now needs to write a concrete class (possibly register it in their dependency injection engine etc.) and maintain the class. and at any time, they are restricted to the values we provide.. the needs always increase and converge to that of a real logging framework. (date, thread id, request, response, exception, error level etc.) because they want to ultimately capture our data and translate to their logging framework data. (xUnit's interface is special for 2 reasons i think: it auto-registers the concrete class and its output seems to have special meaning for the xunit or any test runners)

but it is totally an option to pursue, to open up the library for detailed diagnostics.

here are my 2 cents, if you're looking for other options:

i tend to keep it very simple in my projects, by providing the **.NET Exception** object back to the callers, when an error occurs. The Exception message can contain the exact http error that occured. (e.g. '400 Bad Request. The AppId cannot be empty.' etc.) most often, the callers need no more than this.

also in terms of request/response logging, our callers know the values they passed in, so they kind of know the http request payload values (indirectly). and the http **response** payload translates to a library object (in case of success) or an Exception object with the proper message. (in case of an http failure). so our callers get the information back like any other method call in .NET. they can log that so that our library has no logging concerns.

the last real request/response capturing component i wrote was for a SOAP service.. which lends itself to that sort of message inspector. Rest APIs tend to do that less.

all of the above doesn't mean that there is no logging, it just means that logging is a concern of our consumer app, and they have all the information to totally do that outside of the library.

**Comment by smithrobs** [comment]
Great stuff, both of you.

I can't vote for generating exceptions due to failed REST API calls from the library. I don't want to support the use case where the API should throw an exception to the consuming application, potentially causing an uncaught exception which then terminates the application. There is an opportunity here to impact #7 and how we handle errors in general.

There is merit in providing diagnostic/validation information to the callers. Depending on how user-friendly we aim to be, we could validate all request objects and log (or throw an exception for) incorrect usage.

Since we're now targeting .NET Standard, I'm leaning towards using [Microsoft.Extensions.Logging](https://github.com/aspnet/Logging). The ```web.config``` file support already starts to make use of this. If the consumer wants to have logging, they can provide a logger.

[NexmoResponse](https://github.com/Nexmo/nexmo-dotnet/blob/5561f43e203153961bd41f2d5995a201b41446b8/Nexmo.Api/Request/NexmoResponse.cs) already passes the HTTP status (and in some cases the response) back to the consumer. I agree @rajanadar : the consumer already has the request payload. If we pass back the response then aside from library-specific issues (incorrect configuration, general network error) what else can we log that would be beneficial to the consumer?

**Comment by smithrobs** [comment]
Closing; the mechanism is in place for use when addressing the specifics of #7
