### ISSUE TITLE
Voice API integration with dotNET but why UNAUTHORIZED response?

### ISSUE THREAD

**Issue by ianNexmo** [Nexmo/nexmo-dotnet#98]
Hi,
My customer is struggling to resolve the UNAUTHORIZED issue for integrating the Voice API.

Could anyone help check why this customer is having the UNAUTHORIZED response?
I also attached the screenshot.

![api call](https://user-images.githubusercontent.com/40051809/41140606-6976c2fc-6b29-11e8-9213-e8d47c672793.png)

**Comment by RabebOthmani** [comment]
Hi @ianNexmo ,
I'm going to close this issue as nothing is to be fixed in the Library. 
I've been working with our support team to help the customer. We always recommend using the latest version of the Library to avoid any known issues in the past with the configuration and the API key/secret. 
More details can be found here https://www.nexmo.com/blog/2018/02/28/nexmo-dotnet-client-library-new-release-dr/ or on GitHub https://github.com/Nexmo/nexmo-dotnet/releases/tag/v3.0.0
